// Topuino and Topuino_Server must share this header file

#define CPU_PERCENT "CPU_PERCENT"
#define MEM_PERCENT "MEM_PERCENT"
#define DISK0_PERCENT "DISK_PERCENT"
#define DISK1_PERCENT "DISK1_PERCENT"
#define DISK_READ_RATE "DISK_READ_RATE"
#define DISK_WRITE_RATE "DISK_WRITE_RATE"
#define NET_SENT_RATE "NET_SENT_RATE"
#define NET_RECV_RATE "NET_RECV_RATE"